### ISSUE TITLE
MonsterType value being received by UDP socket in wrong function

### ISSUE THREAD

**Issue by psdev30** [chris-hinson/waste#65]
Check PR #55 for code.

host_listen_for_confirmation from multiplayer_waiting.rs is the guilty function. It receives the MonsterType instead of recv_packets in multiplayer_battle.rs

**Comment by Elsklivet** [comment]
Shouldn't this system no longer be running in the state where battle data is actually being passed?

**Comment by psdev30** [comment]
added break to avoid loop from completing
